[package]
name = "xtask"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
xtask-wasm = { version = "0.1.1", features = ["wasm-opt"] }
app = { path = "../app" }
xshell = "0.1.17"
silkenweb = { git = "https://github.com/silkenweb/silkenweb", features = [
    "server-side-render",
] }
