[package]
name = "xtask"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
xtask-wasm = { version = "0.1.8", features = ["wasm-opt"] }
app = { path = "../app" }
xshell = "0.2.2"
silkenweb = { version = "0.3.0", features = [
    "server-side-render",
] }
env_logger = "0.9.0"
log = "0.4.14"
