[package]
name = "ssr-example-axum-server"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
silkenweb = { workspace = true }
ssr-example-app = { workspace = true }
web-log = { workspace = true }
axum = { version = "0.6.1", features = ["headers"] }
tokio = { version = "1.21.2", features = ["full"] }
tokio-util = { version = "0.7.8", features = ["rt"] }
tower-http = { version = "0.3.4", features = ["fs"] }
