[package]
name = "ssr-example-client-side-rendered"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
silkenweb = { workspace = true }
ssr-example-app = { workspace = true }
wasm-bindgen = { workspace = true }
