[package]
name = "ssr-example-client-side-rendered"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
silkenweb = "0.4.0"
ssr-example-app = { path = "../app" }
wasm-bindgen = "0.2.83"
