[package]
name = "app"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
silkenweb = "0.2.0"
futures-signals = "0.3"
web-log = "1.0.1"
