name: tests
on: [push, pull_request]
jobs:
  stable:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust: [1.65.0]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        target: wasm32-unknown-unknown
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        default: true
        components: clippy
    - uses: Swatinem/rust-cache@v2
      if: ${{ !env.ACT }}
    - run: cargo clippy --all-targets -- -D warnings -D clippy::all
    - run: cargo xtask build
    - run: cargo doc
    - run: cargo test

  nightly:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly-2023-06-06]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        default: true
        components: rustfmt
    - uses: Swatinem/rust-cache@v2
      if: ${{ !env.ACT }}
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-udeps
    - run: cargo fmt --all -- --check
    - run: cargo udeps --all-targets
